### ISSUE TITLE
Pass cookiebot ID as param/option

### ISSUE THREAD

**Issue by jrah** [gietmanic/react-cookiebot#6]
I think it would more optimal for the Cookiebot ID to be passed as a param, .e.g. 

```javascript
import CookieBotLoader from "@danielgietmann/react-cookiebot";

function App() {
  return (
      <html lang="en">
            <body>
                <CookieBotLoader cookieBotId={process.env.COOKIEBOT_ID} />
                {children}
            </body>
        </html>

  )
}
```

Some people might not have their env variables set exactly as `COOKIEBOT_ID`.

Perhaps set `cookieBotUrl` as an optional param. 

This is behaviour that I think most people would expect. Cheers! 🍻

**Comment by danielgtmn** [comment]
Thanks for the suggestion! I will be adding a feature that allows setting the domain via a .env file for more flexibility. However, there are no current plans to implement a function within the component's props for this.

Appreciate your input!
